import type { BotLang } from '../customers';

/**
 * Mijoz botining barcha matnlari (o'zbekcha va ruscha). `ru` obyektining turi `uz` dan olinadi, shuning uchun
 * bir tilda unutilgan yoki ortiqcha kalit kompilyatsiyada chiqadi (test ham kalitlar bir xilligini tekshiradi).
 * Funksiya argumentlari — tayyor, esc() qilingan satrlar: qochirishni chaqiruvchi (customerViews) bajaradi.
 * Holat, to'lov holati va bosqich nomlari bu yerda emas — sayt lug'atida (getDict(lang).order), sayt bilan bir xil chiqsin.
 */
const uz = {
  currency: "so'm",
  more: (n: number) => `… yana ${n} ta`,
  menu: {
    orders: '📦 Buyurtmalarim',
    balance: '💰 Balans',
    requisites: '🏦 Rekvizitlar',
    contacts: '☎️ Aloqa',
    settings: '⚙️ Sozlamalar',
  },
  lang: {
    button: "🇺🇿 O'zbekcha",
    name: "O'zbekcha",
    choose: 'Tilni tanlang:',
    chosen: "✅ Til: O'zbekcha",
    changed: "✅ Til o'zgartirildi, menyu yangilandi.",
  },
  start: {
    hello: (name: string, company: string) => `👋 Assalomu alaykum${name ? `, ${name}` : ''}!\nBu <b>${company}</b> boti: buyurtmalaringiz holati, balansingiz va rekvizitlarimiz shu yerda.`,
    menuHint: "Kerakli bo'limni pastdagi menyudan tanlang.",
    orderTaken: "Bu buyurtma boshqa Telegram hisobiga ulangan. Agar u sizning telefon raqamingizga berilgan bo'lsa, raqamingizni ulashing — buyurtma «📦 Buyurtmalarim» bo'limida ko'rinadi.",
    orderMissing: "Havola bo'yicha buyurtma topilmadi. Havola eskirgan bo'lishi mumkin.",
  },
  phone: {
    why: "Buyurtmalaringiz va balansingizni faqat sizga ko'rsatishimiz uchun telefon raqamingiz kerak. Pastdagi tugmani bosing — raqam Telegram orqali tasdiqlanadi.",
    change: 'Raqam Telegram hisobingizdan olinadi. Pastdagi tugmani bosing — hozirgi raqamingiz ulanadi.',
    share: '📱 Raqamni ulashish',
    later: 'Keyinroq',
    laterNote: "Yaxshi. Raqamni istalgan vaqtda «⚙️ Sozlamalar» bo'limida ulashingiz mumkin.",
    notOwn: "Faqat o'z raqamingizni ulashish mumkin. Buning uchun pastdagi «📱 Raqamni ulashish» tugmasini bosing.",
    typed: 'Yozib yuborilgan raqam qabul qilinmaydi — u Telegram orqali tasdiqlanishi kerak. Pastdagi «📱 Raqamni ulashish» tugmasini bosing.',
    unsupported: (phone: string) => `Kechirasiz, hozircha faqat O'zbekiston raqamlari (+998) qo'llab-quvvatlanadi.${phone ? `\nYordam uchun: ${phone}` : ''}`,
    linked: (phone: string, orders: number) => `✅ Raqamingiz ulandi: <b>${phone}</b>\n${orders > 0 ? `Topilgan buyurtmalar: ${orders} ta.` : "Bu raqam bo'yicha hozircha buyurtma yo'q."}`,
    needForOrders: "Hozircha ulangan buyurtma yo'q. Buyurtmalaringizni ko'rish uchun telefon raqamingizni ulashing.",
    needForBalance: "Balans telefon raqamingiz bo'yicha hisoblanadi. Uni ko'rish uchun raqamingizni ulashing.",
  },
  orders: {
    title: '📦 <b>Buyurtmalarim</b>',
    total: (n: number) => `jami ${n} ta`,
    page: (page: number, pages: number) => `Sahifa ${page} / ${pages}`,
    hint: "Batafsil ko'rish uchun buyurtma raqamini bosing.",
    linkHint: "Barcha buyurtmalaringizni ko'rish uchun «⚙️ Sozlamalar» bo'limida telefon raqamingizni ulashing.",
    empty: (site: string) => `Hozircha buyurtmalaringiz yo'q.\n🛒 Buyurtma berish: ${site}`,
  },
  card: {
    title: (id: number) => `Buyurtma #${id}`,
    registered: (date: string) => `Ro'yxatga olingan: ${date}`,
    history: 'Tarix',
    due: (date: string) => `To'lov muddati: ${date}`,
    remaining: (sum: string) => `Qoldiq: ${sum}`,
    invoicePaid: "To'liq to'langan ✅",
    notFound: 'Buyurtma topilmadi.',
    open: '🌐 Saytda ochish',
    invoice: '🧾 Hisob-faktura',
    pay: "💳 To'lash",
    refresh: '🔄 Yangilash',
    refreshed: 'Yangilandi ✅',
    back: '◀️ Buyurtmalar',
  },
  payMethod: {
    cash: 'Naqd',
    payme: 'Payme',
    click: 'Click',
    bank_transfer: "Bank o'tkazmasi",
  },
  balance: {
    title: '💰 <b>Balans</b>',
    total: (sum: string) => `Jami to'lanishi kerak: <b>${sum}</b>`,
    noDebt: "Qarzingiz yo'q ✅",
    invoices: 'Hisob-fakturalar',
    order: (id: number) => `buyurtma #${id}`,
    remaining: (sum: string) => `qoldiq ${sum}`,
    due: (date: string) => `muddat ${date}`,
    overdue: "⚠️ muddati o'tgan",
    overdueTotal: (sum: string) => `⚠️ Shundan muddati o'tgan: <b>${sum}</b>`,
    unpaidOrders: "To'lanmagan buyurtmalar",
    method: {
      cash: 'naqd, yetkazishda',
      cashPickup: 'naqd, olib ketishda',
      bank_transfer: "bank o'tkazmasi",
      online: "onlayn to'lov tugallanmagan",
      other: "to'lov kutilmoqda",
    },
    contract: (no: string) => `Shartnoma ${no}`,
    limit: (sum: string) => `Nasiya limiti: ${sum}`,
    noLimit: 'Nasiya limiti belgilanmagan.',
    used: (sum: string) => `Foydalanilgan: ${sum}`,
    available: (sum: string) => `Mavjud: ${sum}`,
    term: (days: number) => `To'lov muddati: ${days} kun`,
    note: "Balans — to'lanishi kerak bo'lgan summa: hisob-fakturalar qoldig'i va to'lanmagan buyurtmalar.",
  },
  requisites: {
    title: '🏦 <b>Rekvizitlar</b>',
    inn: 'STIR',
    director: 'Direktor',
    address: 'Manzil',
    phone: 'Telefon',
    purpose: "ℹ️ To'lov maqsadida hisob-faktura raqamini ko'rsating.",
    onRequest: (phone: string) => `Rekvizitlarni so'rovingiz bo'yicha menejer yuboradi.${phone ? `\n📞 ${phone}` : ''}`,
  },
  contacts: {
    title: '☎️ <b>Aloqa</b>',
    hours: 'Ish vaqti',
    site: 'Sayt',
    channel: 'Telegram kanal',
  },
  settings: {
    title: '⚙️ <b>Sozlamalar</b>',
    lang: (name: string) => `Til: ${name}`,
    notifyOn: 'Xabarnomalar: yoqilgan',
    notifyOff: "Xabarnomalar: o'chirilgan",
    phone: (masked: string) => `Telefon: ${masked}`,
    noPhone: 'Telefon: ulanmagan',
    turnOn: '🔔 Xabarnomalarni yoqish',
    turnOff: "🔕 Xabarnomalarni o'chirish",
    turnedOn: 'Xabarnomalar yoqildi 🔔',
    turnedOff: "Xabarnomalar o'chirildi 🔕",
    changePhone: '📱 Raqamni yangilash',
    stop: '🚪 Botdan chiqish',
  },
  stop: {
    confirm: 'Botdan chiqmoqchimisiz?\nTelefon raqamingiz va buyurtmalaringiz bu chatdan uziladi, xabarnomalar kelmaydi.',
    yes: 'Ha, chiqaman',
    no: "Yo'q, qolaman",
    done: 'Botdan chiqdingiz.',
    bye: "Botdagi ma'lumotlaringiz uzildi: telefon raqamingiz va buyurtmalaringiz endi bu chatga bog'lanmagan.\nQayta ulanish uchun /start bosing. Salomat bo'ling!",
  },
  help: (phone: string, ai = false) => [
    'ℹ️ <b>Yordam</b>',
    '',
    '📦 /orders — buyurtmalarim va ularning holati',
    "💰 /balance — balans: to'lanishi kerak bo'lgan summa",
    '🌐 /lang — tilni tanlash',
    '🚪 /stop — botdan chiqish',
    '',
    "Buyurtma holati o'zgarsa, o'zimiz xabar yuboramiz.",
    ai ? "✍️ Savolingizni oddiy matn bilan yozsangiz, sun'iy intellekt yordamchisi javob beradi (buyurtma, to'lov, mahsulot va yetkazib berish haqida)." : null,
    phone ? `Savollar bo'lsa: ${phone}` : null,
  ].filter((l) => l !== null).join('\n'),
  fallback: "Hozircha faqat menyudagi bo'limlar bo'yicha yordam bera olaman. Pastdagi tugmalardan birini tanlang yoki /help bosing.",
  ai: {
    hint: 'Savolingizni matn bilan yozing yoki pastdagi tugmalardan birini tanlang.',
    busy: 'Oldingi savolingizga javob tayyorlanmoqda, biroz kuting.',
    limit: "Bugungi savollar soni chegarasiga yetdi. Ertaga yana yozishingiz mumkin; hozircha pastdagi menyudan foydalaning yoki «Aloqa» bo'limidagi raqamga qo'ng'iroq qiling.",
    unavailable: "Kechirasiz, bu savolga hozir javob bera olmadim. Pastdagi menyudan foydalaning yoki «Aloqa» bo'limidagi raqam orqali menejer bilan bog'laning.",
  },
  error: "Kechirasiz, xatolik yuz berdi. Birozdan keyin qayta urinib ko'ring.",
};

export type CustomerTexts = typeof uz;

const ru: CustomerTexts = {
  currency: 'сум',
  more: (n) => `… ещё ${n}`,
  menu: {
    orders: '📦 Мои заказы',
    balance: '💰 Баланс',
    requisites: '🏦 Реквизиты',
    contacts: '☎️ Контакты',
    settings: '⚙️ Настройки',
  },
  lang: {
    button: '🇷🇺 Русский',
    name: 'Русский',
    choose: 'Выберите язык:',
    chosen: '✅ Язык: Русский',
    changed: '✅ Язык изменён, меню обновлено.',
  },
  start: {
    hello: (name, company) => `👋 Здравствуйте${name ? `, ${name}` : ''}!\nЭто бот <b>${company}</b>: здесь статус ваших заказов, баланс и наши реквизиты.`,
    menuHint: 'Выберите нужный раздел в меню ниже.',
    orderTaken: 'Этот заказ привязан к другому аккаунту Telegram. Если он оформлен на ваш номер телефона, поделитесь номером — заказ появится в разделе «📦 Мои заказы».',
    orderMissing: 'Заказ по ссылке не найден. Возможно, ссылка устарела.',
  },
  phone: {
    why: 'Номер телефона нужен, чтобы показывать заказы и баланс только вам. Нажмите кнопку ниже — номер подтвердится через Telegram.',
    change: 'Номер берётся из вашего аккаунта Telegram. Нажмите кнопку ниже — привяжется ваш текущий номер.',
    share: '📱 Поделиться номером',
    later: 'Позже',
    laterNote: 'Хорошо. Привязать номер можно в любой момент в разделе «⚙️ Настройки».',
    notOwn: 'Привязать можно только свой номер. Для этого нажмите кнопку «📱 Поделиться номером» ниже.',
    typed: 'Номер, отправленный текстом, не принимается — он должен быть подтверждён через Telegram. Нажмите кнопку «📱 Поделиться номером» ниже.',
    unsupported: (phone) => `К сожалению, пока поддерживаются только номера Узбекистана (+998).${phone ? `\nПомощь: ${phone}` : ''}`,
    linked: (phone, orders) => `✅ Номер привязан: <b>${phone}</b>\n${orders > 0 ? `Найдено заказов: ${orders}.` : 'Заказов по этому номеру пока нет.'}`,
    needForOrders: 'Привязанных заказов пока нет. Чтобы увидеть свои заказы, поделитесь номером телефона.',
    needForBalance: 'Баланс считается по вашему номеру телефона. Чтобы увидеть его, поделитесь номером.',
  },
  orders: {
    title: '📦 <b>Мои заказы</b>',
    total: (n) => `всего: ${n}`,
    page: (page, pages) => `Страница ${page} / ${pages}`,
    hint: 'Нажмите на номер заказа, чтобы открыть подробности.',
    linkHint: 'Чтобы увидеть все свои заказы, привяжите номер телефона в разделе «⚙️ Настройки».',
    empty: (site) => `У вас пока нет заказов.\n🛒 Оформить заказ: ${site}`,
  },
  card: {
    title: (id) => `Заказ #${id}`,
    registered: (date) => `Зарегистрирован: ${date}`,
    history: 'История',
    due: (date) => `Срок оплаты: ${date}`,
    remaining: (sum) => `Остаток: ${sum}`,
    invoicePaid: 'Оплачен полностью ✅',
    notFound: 'Заказ не найден.',
    open: '🌐 Открыть на сайте',
    invoice: '🧾 Счёт-фактура',
    pay: '💳 Оплатить',
    refresh: '🔄 Обновить',
    refreshed: 'Обновлено ✅',
    back: '◀️ Заказы',
  },
  payMethod: {
    cash: 'Наличные',
    payme: 'Payme',
    click: 'Click',
    bank_transfer: 'Перечисление',
  },
  balance: {
    title: '💰 <b>Баланс</b>',
    total: (sum) => `Всего к оплате: <b>${sum}</b>`,
    noDebt: 'Задолженности нет ✅',
    invoices: 'Счета-фактуры',
    order: (id) => `заказ #${id}`,
    remaining: (sum) => `остаток ${sum}`,
    due: (date) => `срок ${date}`,
    overdue: '⚠️ просрочен',
    overdueTotal: (sum) => `⚠️ Из них просрочено: <b>${sum}</b>`,
    unpaidOrders: 'Неоплаченные заказы',
    method: {
      cash: 'наличными при доставке',
      cashPickup: 'наличными при самовывозе',
      bank_transfer: 'перечислением',
      online: 'онлайн-оплата не завершена',
      other: 'ожидает оплаты',
    },
    contract: (no) => `Договор ${no}`,
    limit: (sum) => `Кредитный лимит: ${sum}`,
    noLimit: 'Кредитный лимит не установлен.',
    used: (sum) => `Использовано: ${sum}`,
    available: (sum) => `Доступно: ${sum}`,
    term: (days) => `Срок оплаты: ${days} дн.`,
    note: 'Баланс — это сумма к оплате: остаток по счетам-фактурам и неоплаченные заказы.',
  },
  requisites: {
    title: '🏦 <b>Реквизиты</b>',
    inn: 'ИНН',
    director: 'Директор',
    address: 'Адрес',
    phone: 'Телефон',
    purpose: 'ℹ️ В назначении платежа укажите номер счёта-фактуры.',
    onRequest: (phone) => `Реквизиты по вашему запросу отправит менеджер.${phone ? `\n📞 ${phone}` : ''}`,
  },
  contacts: {
    title: '☎️ <b>Контакты</b>',
    hours: 'Время работы',
    site: 'Сайт',
    channel: 'Telegram-канал',
  },
  settings: {
    title: '⚙️ <b>Настройки</b>',
    lang: (name) => `Язык: ${name}`,
    notifyOn: 'Уведомления: включены',
    notifyOff: 'Уведомления: выключены',
    phone: (masked) => `Телефон: ${masked}`,
    noPhone: 'Телефон: не привязан',
    turnOn: '🔔 Включить уведомления',
    turnOff: '🔕 Выключить уведомления',
    turnedOn: 'Уведомления включены 🔔',
    turnedOff: 'Уведомления выключены 🔕',
    changePhone: '📱 Обновить номер',
    stop: '🚪 Выйти из бота',
  },
  stop: {
    confirm: 'Выйти из бота?\nВаш номер телефона и заказы будут отвязаны от этого чата, уведомления приходить не будут.',
    yes: 'Да, выйти',
    no: 'Нет, остаться',
    done: 'Вы вышли из бота.',
    bye: 'Ваши данные в боте отвязаны: номер телефона и заказы больше не связаны с этим чатом.\nЧтобы подключиться снова, нажмите /start. Всего доброго!',
  },
  help: (phone, ai = false) => [
    'ℹ️ <b>Помощь</b>',
    '',
    '📦 /orders — мои заказы и их статус',
    '💰 /balance — баланс: сумма к оплате',
    '🌐 /lang — выбор языка',
    '🚪 /stop — выйти из бота',
    '',
    'Когда статус заказа изменится, мы сами пришлём сообщение.',
    ai ? '✍️ Напишите вопрос обычным текстом — ответит помощник на основе искусственного интеллекта (заказы, оплата, товары, доставка).' : null,
    phone ? `Если есть вопросы: ${phone}` : null,
  ].filter((l) => l !== null).join('\n'),
  fallback: 'Пока я могу помочь только по разделам меню. Выберите кнопку ниже или нажмите /help.',
  ai: {
    hint: 'Напишите вопрос текстом или выберите кнопку ниже.',
    busy: 'Готовлю ответ на предыдущий вопрос, подождите немного.',
    limit: 'На сегодня лимит вопросов исчерпан. Завтра можно написать снова; пока воспользуйтесь меню ниже или позвоните по номеру из раздела «Контакты».',
    unavailable: 'Извините, сейчас не получилось ответить на этот вопрос. Воспользуйтесь меню ниже или свяжитесь с менеджером по номеру из раздела «Контакты».',
  },
  error: 'Извините, произошла ошибка. Попробуйте ещё раз чуть позже.',
};

export const customerTexts: Record<BotLang, CustomerTexts> = { uz, ru };
